restore flake-update

diff --git a/bin/flake-update b/bin/flake-update
--- a/bin/flake-update
+++ b/bin/flake-update
@@ -1,7 +1,17 @@
 #! /usr/bin/env fish
 
 function flake-update
-    set UPDATE_DIR $PWD
+    set -g UPDATE_DIR (mktemp -d -t flake-update)
+    cd $UPDATE_DIR || return 1
+    git clone git@github.com:Lillecarl/nixos.git
+    cd nixos || return 1
+    direnv allow || return 1
+
+    ./update.py || begin
+        echo "Failed to update flake"
+        return 1
+    end
+
     echo Building
     set broken
     for host in nub shitbox
@@ -19,6 +29,7 @@ function flake-update
     echo Gitting
     git add . || return 1
     git restore --staged .flakepath || return 1
+    git restore --staged bin/flake-update || return 1
     git commit -m 'Maintenance
 
 Update flake inputs
